// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ox1oZrObxt3tgf60HS3PB-AXG7yLkOk',
    appId: '1:916318379656:web:35db84fa117d8541a1893d',
    messagingSenderId: '916318379656',
    projectId: 'framefinder-f7818',
    authDomain: 'framefinder-f7818.firebaseapp.com',
    storageBucket: 'framefinder-f7818.appspot.com',
    measurementId: 'G-RWKFSJ2C8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JEB_8X_VY238vrjKQfilcI8dYWdzjuM',
    appId: '1:916318379656:android:5ff04d20988d97f6a1893d',
    messagingSenderId: '916318379656',
    projectId: 'framefinder-f7818',
    storageBucket: 'framefinder-f7818.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKc--GKNHcaCR0WfRXrviLnHJiE5ILzc',
    appId: '1:916318379656:ios:9d412809cc7775fba1893d',
    messagingSenderId: '916318379656',
    projectId: 'framefinder-f7818',
    storageBucket: 'framefinder-f7818.appspot.com',
    iosClientId: '916318379656-5p1u0vsqabonm17c4urehp5g7stt35da.apps.googleusercontent.com',
    iosBundleId: 'com.example.framefinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPKc--GKNHcaCR0WfRXrviLnHJiE5ILzc',
    appId: '1:916318379656:ios:e7cd1b5df860d692a1893d',
    messagingSenderId: '916318379656',
    projectId: 'framefinder-f7818',
    storageBucket: 'framefinder-f7818.appspot.com',
    iosClientId: '916318379656-ofe976diulbn7hkhoj7ucp7lc46k9jno.apps.googleusercontent.com',
    iosBundleId: 'com.example.framefinder.RunnerTests',
  );
}
